import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-screen min-h-screen relative pb-12`}
      >
        <div className="w-full h-12 flex flex-row items-center border-b border-gray-300">
          <h1 className="w-full text-center text-2xl font-bold">Family Storage</h1>
        </div>
        {children}
        <Toaster richColors position="top-center" duration={2000} />
        <Navbar />
      </body>
    </html>
  );
}
